---
- name: Install Node.js using NVM
  hosts: test-server
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - curl

    - name: Download and install NVM
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        source ~/.bashrc
      args:
        executable: /bin/bash

    - name: Install Node.js LTS using NVM
      shell: |
        nvm install --lts
        nvm use --lts
      args:
        executable: /bin/bash

    - name: Install npm
      apt:
        name: npm
        state: present
